name: wependio
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  video_player: ^2.4.6
  adaptive_theme: ^3.1.1
  auth_buttons: ^2.0.4
  # glass_kit: ^2.0.1
  otp_text_field: ^1.1.3
  animated_toggle_switch: ^0.5.2
  shared_preferences: ^2.0.15
  local_hero: ^0.2.0
  curved_navigation_bar: ^1.0.3
  google_maps_flutter: ^2.1.10
  custom_marker: ^1.0.0
  maps_curved_line: ^1.0.2
  animations: ^2.0.4
  # glassmorphism: ^3.0.0
  # glassmorphism_ui: ^0.3.0
  glass: ^1.0.1+1
  device_preview: ^1.1.0
  flutter_otp_text_field: ^1.1.0+2
  timelines: ^0.1.0
  timeline_tile: ^2.0.0
  modal_bottom_sheet: ^2.1.2
  image_stack: ^2.1.1
  avatar_stack: ^1.1.2
  flutter_svg: ^1.0.3
  syncfusion_flutter_maps: ^20.2.49
  flutter_map: ^2.2.0
  vector_map_tiles: ^2.4.1
  latlong2: ^0.8.1
  flutter_staggered_grid_view: ^0.6.2
  flutter_carousel_slider: ^1.0.9
  blurrycontainer: ^1.0.2
  animate_do: ^2.1.0
  intl: ^0.17.0
  http: ^0.13.5
  top_snackbar_flutter: ^2.1.1
  flutter_slidable: ^2.0.0
  share_plus: ^4.1.0
  url_launcher: ^6.1.5
  custom_bottom_sheet: ^1.1.2
  widget_loading: ^0.3.2
  image_picker: ^0.8.5+3
  expandable_bottom_sheet: ^1.1.1+1
  responsive_sizer: ^3.1.1

  # dropdown_button2: ^1.8.2
  cached_network_image: ^3.2.1
flutter_native_splash:
  color: "#f5f5f5"
  color_dark: "#000000"
  image: Assets/Images/wependiosmall.png
  android: true
  ios: true
flutter_icons:
  android: true
  ios: true
  adaptive_icons_background: "#7C94CB"
  image_path: "Assets/Images/wependiologo1.png"
dev_dependencies:
  flutter_native_splash: ^1.2.3
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - Assets/Images/
    - Assets/Fonts/
    - Assets/style/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: greycliffcf
      fonts:
        # - asset: Assets/Fonts/greycliffcf-thin.otf
        #   weight: 100
        # - asset: Assets/Fonts/greycliffcf-thinoblique.otf
        #   weight: 100
        #   style: italic
        # - asset: Assets/Fonts/greycliffcf-extralight.otf
        #   weight: 200
        # - asset: Assets/Fonts/greycliffcf-extralightoblique.otf
        #   weight: 200
        #   style: italic
        - asset: Assets/Fonts/greycliffcf-light.otf
          weight: 300
        - asset: Assets/Fonts/greycliffcf-lightoblique.otf
          weight: 300
          style: italic
        - asset: Assets/Fonts/greycliffcf-regular.otf
          weight: 400
        - asset: Assets/Fonts/greycliffcf-regularoblique.otf
          weight: 400
          style: italic
        - asset: Assets/Fonts/greycliffcf-medium.otf
          weight: 500
        - asset: Assets/Fonts/greycliffcf-mediumoblique.otf
          weight: 500
          style: italic
        - asset: Assets/Fonts/greycliffcf-DemiBold.otf
          weight: 600
        - asset: Assets/Fonts/greycliffcf-demiboldoblique.otf
          weight: 600
          style: italic
        - asset: Assets/Fonts/greycliffcf-bold.otf
          weight: 700
        - asset: Assets/Fonts/greycliffcf-boldoblique.otf
          weight: 700
          style: italic
        - asset: Assets/Fonts/greycliffcf-ExtraBold.otf
          weight: 800
        - asset: Assets/Fonts/greycliffcf-extraboldoblique.otf
          weight: 800
          style: italic
        - asset: Assets/Fonts/greycliffcf-heavy.otf
          weight: 900
        - asset: Assets/Fonts/greycliffcf-heavyoblique.otf
          weight: 900
          style: italic
          

        

    - family: WorkSans
      fonts:
        - asset: Assets/Fonts/WorkSans-Regular.ttf
        - asset: Assets/Fonts/WorkSans-SemiBold.ttf
          weight: 400

    - family: nunito
      fonts:    
        - asset: Assets/Fonts/nunito-sans.regular.ttf

    - family: SFPRO
      fonts:    
        - asset: Assets/Fonts/SF-Pro-Text-Regular.ttf


        
       
          
        
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
